// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package room

import (
	"game/internal/common"
	"game/proto/pb"

	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

const (
	RoomNewReq        kiwi.TCode = 0
	RoomNewRes        kiwi.TCode = 1
	RoomListReq       kiwi.TCode = 2
	RoomListRes       kiwi.TCode = 3
	RoomEntryReq      kiwi.TCode = 4
	RoomEntryRes      kiwi.TCode = 5
	RoomEntryPus      kiwi.TCode = 6
	RoomExitReq       kiwi.TCode = 7
	RoomExitRes       kiwi.TCode = 8
	RoomExitPus       kiwi.TCode = 9
	RoomReadyReq      kiwi.TCode = 10
	RoomReadyRes      kiwi.TCode = 11
	RoomReadyPus      kiwi.TCode = 12
	RoomStartReq      kiwi.TCode = 13
	RoomStartRes      kiwi.TCode = 14
	RoomStartPus      kiwi.TCode = 15
	RoomGetReq        kiwi.TCode = 16
	RoomGetRes        kiwi.TCode = 17
	RoomModifyReq     kiwi.TCode = 18
	RoomModifyRes     kiwi.TCode = 19
	RoomModifyPus     kiwi.TCode = 20
	RoomReconnectReq  kiwi.TCode = 21
	RoomReconnectRes  kiwi.TCode = 22
	RoomDisconnectPus kiwi.TCode = 23
	RoomReconnectPus  kiwi.TCode = 24
)

func (svc *svc) bindCodecFac() {
	kiwi.Codec().BindFac(common.Room, RoomNewReq, func() util.IMsg {
		return &pb.RoomNewReq{}
	})
	kiwi.Codec().BindFac(common.Room, RoomNewRes, func() util.IMsg {
		return &pb.RoomNewRes{}
	})
	kiwi.Codec().BindFac(common.Room, RoomListReq, func() util.IMsg {
		return &pb.RoomListReq{}
	})
	kiwi.Codec().BindFac(common.Room, RoomListRes, func() util.IMsg {
		return &pb.RoomListRes{}
	})
	kiwi.Codec().BindFac(common.Room, RoomEntryReq, func() util.IMsg {
		return &pb.RoomEntryReq{}
	})
	kiwi.Codec().BindFac(common.Room, RoomEntryRes, func() util.IMsg {
		return &pb.RoomEntryRes{}
	})
	kiwi.Codec().BindFac(common.Room, RoomEntryPus, func() util.IMsg {
		return &pb.RoomEntryPus{}
	})
	kiwi.Codec().BindFac(common.Room, RoomExitReq, func() util.IMsg {
		return &pb.RoomExitReq{}
	})
	kiwi.Codec().BindFac(common.Room, RoomExitRes, func() util.IMsg {
		return &pb.RoomExitRes{}
	})
	kiwi.Codec().BindFac(common.Room, RoomExitPus, func() util.IMsg {
		return &pb.RoomExitPus{}
	})
	kiwi.Codec().BindFac(common.Room, RoomReadyReq, func() util.IMsg {
		return &pb.RoomReadyReq{}
	})
	kiwi.Codec().BindFac(common.Room, RoomReadyRes, func() util.IMsg {
		return &pb.RoomReadyRes{}
	})
	kiwi.Codec().BindFac(common.Room, RoomReadyPus, func() util.IMsg {
		return &pb.RoomReadyPus{}
	})
	kiwi.Codec().BindFac(common.Room, RoomStartReq, func() util.IMsg {
		return &pb.RoomStartReq{}
	})
	kiwi.Codec().BindFac(common.Room, RoomStartRes, func() util.IMsg {
		return &pb.RoomStartRes{}
	})
	kiwi.Codec().BindFac(common.Room, RoomStartPus, func() util.IMsg {
		return &pb.RoomStartPus{}
	})
	kiwi.Codec().BindFac(common.Room, RoomGetReq, func() util.IMsg {
		return &pb.RoomGetReq{}
	})
	kiwi.Codec().BindFac(common.Room, RoomGetRes, func() util.IMsg {
		return &pb.RoomGetRes{}
	})
	kiwi.Codec().BindFac(common.Room, RoomModifyReq, func() util.IMsg {
		return &pb.RoomModifyReq{}
	})
	kiwi.Codec().BindFac(common.Room, RoomModifyRes, func() util.IMsg {
		return &pb.RoomModifyRes{}
	})
	kiwi.Codec().BindFac(common.Room, RoomModifyPus, func() util.IMsg {
		return &pb.RoomModifyPus{}
	})
	kiwi.Codec().BindFac(common.Room, RoomReconnectReq, func() util.IMsg {
		return &pb.RoomReconnectReq{}
	})
	kiwi.Codec().BindFac(common.Room, RoomReconnectRes, func() util.IMsg {
		return &pb.RoomReconnectRes{}
	})
	kiwi.Codec().BindFac(common.Room, RoomDisconnectPus, func() util.IMsg {
		return &pb.RoomDisconnectPus{}
	})
	kiwi.Codec().BindFac(common.Room, RoomReconnectPus, func() util.IMsg {
		return &pb.RoomReconnectPus{}
	})
}
