// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package room

const (
	//房间名已存在
	EcRoomNew_ExistName = 1
	//房间不存在
	EcRoomEntry_NotExistRoomId = 1
	//房间已满
	EcRoomEntry_RoomFull = 2
	//不能进入该房间
	EcRoomEntry_CurrStatusCanNotEntry = 3
	//已进入房间，不能再进入
	EcRoomEntry_HadEntered = 4
	//房间不存在
	EcRoomExit_NotExistRoomId = 1
	//没有进房间
	EcRoomExit_NotEntryRoom = 2
	//不能退出房间
	EcRoomExit_CanNotExitRoom = 3
	//房间不存在
	EcRoomReady_NotExistRoomId = 1
	//没有进房间
	EcRoomReady_NotEntryRoom = 2
	//房间不存在或不是房主
	EcRoomStart_NotExistRoomOrNotOwner = 1
	//没有进房间
	EcRoomStart_NotEntryRoom = 2
	//有玩家没准备
	EcRoomStart_SomebodyNotReady = 3
	//创建场景失败
	EcRoomStart_CreateSceneFail = 4
	//房间不存在
	EcRoomGet_NotExistRoomId = 1
	//没有进房间
	EcRoomModify_NotEntryRoom = 1
	//不是管理员
	EcRoomModify_NotOwner = 2
	//房间不存在
	EcRoomReconnect_NotExistRoomId = 1
	//已被提出
	EcRoomReconnect_KickOut = 2
)
