// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package room

import (
	"github.com/15mga/kiwi/util/mgo"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

const (
	SchemaRoom = "room"
)

const (
	Id          = "_id"
	CreateTime  = "create_time"
	CurrPlayers = "curr_players"
	MaxPlayers  = "max_players"
	Mode        = "mode"
	Name        = "name"
	OwnerId     = "owner_id"
	Password    = "password"
	Players     = "players"
	SceneTplId  = "scene_tpl_id"
	Status      = "status"

	RoomPlayerDisconnect = "disconnect"
	RoomPlayerEnterTs    = "enter_ts" //进入的时间戳
	RoomPlayerReady      = "ready"
	RoomPlayerSeat       = "seat"
)

func (s *svc) initColl() {
	mgo.InitColl(SchemaRoom, RoomIdx)
}

func RoomIdx() []mongo.IndexModel {
	return []mongo.IndexModel{
		{
			Keys: bson.D{
				{"name", "text"},
			},
			Options: options.Index().
				SetUnique(true),
		},
		{
			Keys: bson.D{
				{"name", 1},
				{"mode", 1},
				{"scene_tpl_id", 1},
				{"private", 1},
				{"status", 1},
			},
		},
	}
}
