// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package room

import (
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

func (s *svc) OnRoomNew(pkt kiwi.IRcvRequest, req *pb.RoomNewReq, res *pb.RoomNewRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnRoomList(pkt kiwi.IRcvRequest, req *pb.RoomListReq, res *pb.RoomListRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnRoomEntry(pkt kiwi.IRcvRequest, req *pb.RoomEntryReq, res *pb.RoomEntryRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnRoomExit(pkt kiwi.IRcvRequest, req *pb.RoomExitReq, res *pb.RoomExitRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnRoomReady(pkt kiwi.IRcvRequest, req *pb.RoomReadyReq, res *pb.RoomReadyRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnRoomStart(pkt kiwi.IRcvRequest, req *pb.RoomStartReq, res *pb.RoomStartRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnRoomGet(pkt kiwi.IRcvRequest, req *pb.RoomGetReq, res *pb.RoomGetRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnRoomModify(pkt kiwi.IRcvRequest, req *pb.RoomModifyReq, res *pb.RoomModifyRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnRoomReconnect(pkt kiwi.IRcvRequest, req *pb.RoomReconnectReq, res *pb.RoomReconnectRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}
