// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package scene

import (
	"github.com/15mga/kiwi/util/mgo"
	"go.mongodb.org/mongo-driver/mongo"
)

const (
	SchemaSceneTemplate = "scene_template"
)

const (
	SceneAdmitted = "admitted" //准入玩家
	SceneId       = "id"
	SceneMode     = "mode"
	SceneTplId    = "tpl_id"

	SceneAdmittedPlayerEntered = "entered"
	SceneAdmittedPlayerId      = "id"

	SceneEventId        = "id"
	SceneEventInvisible = "invisible"
	SceneEventMovement  = "movement"
	SceneEventSkill     = "skill"
	SceneEventVisible   = "visible"

	SceneInvisibleTimestamp = "timestamp" //时间戳,unix millSec

	SceneMonsterTplId = "tpl_id"

	SceneMovementDuration  = "duration"
	SceneMovementPosition  = "position"  //位置
	SceneMovementTimestamp = "timestamp" //时间戳,unix millSec

	ScenePlayerAvatar = "avatar"
	ScenePlayerGender = "gender"
	ScenePlayerHero   = "hero" //玩家英雄角色
	ScenePlayerNick   = "nick"
	ScenePlayerTeamId = "team_id"

	SceneSkillPosition  = "position"
	SceneSkillSkillId   = "skill_id"
	SceneSkillTargetId  = "target_id"
	SceneSkillTimestamp = "timestamp" //时间戳,unix millSec

	SceneTemplateId     = "_id"
	SceneTemplateHeight = "height"
	SceneTemplateName   = "name"
	SceneTemplateWidth  = "width"

	SceneVisibleGateAddr   = "gate_addr"
	SceneVisibleGateNodeId = "gate_node_id"
	SceneVisibleMonster    = "monster"
	SceneVisiblePlayer     = "player"
	SceneVisiblePosition   = "position"
	SceneVisibleTimestamp  = "timestamp" //时间戳,unix millSec
)

func (s *svc) initColl() {
	mgo.InitColl(SchemaSceneTemplate, SceneTemplateIdx)
}

func SceneTemplateIdx() []mongo.IndexModel {
	return []mongo.IndexModel{}
}
