// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package scene

import (
	"github.com/15mga/kiwi/util/mgo"
	"go.mongodb.org/mongo-driver/mongo"
)

const (
	SchemaSceneTemplate = "scene_template"
)

const (
	BehaviourAreaSkillPosition = "position"
	BehaviourAreaSkillSkillId  = "skill_id"

	BehaviourTargetSkillSkillId  = "skill_id"
	BehaviourTargetSkillTargetId = "target_id"

	SceneAdmitted = "admitted" //准入玩家
	SceneId       = "id"
	SceneMode     = "mode"
	SceneTplId    = "tpl_id"

	SceneAdmittedPlayerEntered = "entered"
	SceneAdmittedPlayerId      = "id"

	SceneBehaviourAreaSkill = "area_skill"
	SceneBehaviourIdle      = "idle"
	SceneBehaviourPawnSkill = "pawn_skill"
	SceneBehaviourRun       = "run"
	SceneBehaviourTimestamp = "timestamp" //行为的时间戳,unix millSec

	SceneBehaviourEvtBehaviour = "behaviour"
	SceneBehaviourEvtPawnId    = "pawn_id"

	SceneEvtMovement = "movement"

	SceneMonsterTplId = "tpl_id"

	SceneMovementDuration = "duration" //移动的时间,单位毫秒
	SceneMovementPosition = "position" //方向模

	SceneMovementEvtMovement = "movement"
	SceneMovementEvtPawnId   = "pawn_id"

	ScenePawnPawn             = "pawn"
	ScenePawnPlayerGateAddr   = "player_gate_addr"
	ScenePawnPlayerGateNodeId = "player_gate_node_id"

	ScenePawnEvtMonster  = "monster"
	ScenePawnEvtPawnId   = "pawn_id"
	ScenePawnEvtPlayer   = "player"
	ScenePawnEvtPosition = "position"

	ScenePlayerAvatar = "avatar"
	ScenePlayerGender = "gender"
	ScenePlayerHero   = "hero" //玩家英雄角色
	ScenePlayerNick   = "nick"
	ScenePlayerTeamId = "team_id"

	SceneTemplateId     = "_id"
	SceneTemplateHeight = "height"
	SceneTemplateName   = "name"
	SceneTemplateWidth  = "width"
)

func (s *svc) initColl() {
	mgo.InitColl(SchemaSceneTemplate, SceneTemplateIdx)
}

func SceneTemplateIdx() []mongo.IndexModel {
	return []mongo.IndexModel{}
}
