// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package scene

import (
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

func (s *svc) OnSceneEntry(pkt kiwi.IRcvRequest, req *pb.SceneEntryReq, res *pb.SceneEntryRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnSceneMovement(pkt kiwi.IRcvRequest, req *pb.SceneMovementReq, res *pb.SceneMovementRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnSceneBehaviour(pkt kiwi.IRcvRequest, req *pb.SceneBehaviourReq, res *pb.SceneBehaviourRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnSceneRobotAdd(pkt kiwi.IRcvRequest, req *pb.SceneRobotAddReq, res *pb.SceneRobotAddRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnSceneRobotClear(pkt kiwi.IRcvRequest, req *pb.SceneRobotClearReq, res *pb.SceneRobotClearRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnNewScene(pkt kiwi.IRcvRequest, req *pb.NewSceneReq, res *pb.NewSceneRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnDisposeScene(pkt kiwi.IRcvRequest, req *pb.DisposeSceneReq, res *pb.DisposeSceneRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnSceneGet(pkt kiwi.IRcvRequest, req *pb.SceneGetReq, res *pb.SceneGetRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnSceneHas(pkt kiwi.IRcvRequest, req *pb.SceneHasReq, res *pb.SceneHasRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}
