// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package scene

import (
	"game/internal/common"
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/core"
)

func (s *svc) registerReq() {
	kiwi.Router().BindReq(common.Scene, SceneEntryReq, func(req kiwi.IRcvRequest) {
		core.SharePrcReq[*pb.SceneEntryReq](req, common.SScene, _svc.OnSceneEntry)
	})
	kiwi.Router().BindReq(common.Scene, SceneMovementReq, func(req kiwi.IRcvRequest) {
		core.SharePrcReq[*pb.SceneMovementReq](req, common.SScene, _svc.OnSceneMovement)
	})
	kiwi.Router().BindReq(common.Scene, SceneBehaviourReq, func(req kiwi.IRcvRequest) {
		core.SharePrcReq[*pb.SceneBehaviourReq](req, common.SScene, _svc.OnSceneBehaviour)
	})
	kiwi.Router().BindReq(common.Scene, SceneRobotAddReq, func(req kiwi.IRcvRequest) {
		core.SharePrcReq[*pb.SceneRobotAddReq](req, common.SScene, _svc.OnSceneRobotAdd)
	})
	kiwi.Router().BindReq(common.Scene, SceneRobotClearReq, func(req kiwi.IRcvRequest) {
		core.SharePrcReq[*pb.SceneRobotClearReq](req, common.SScene, _svc.OnSceneRobotClear)
	})
	kiwi.Router().BindReq(common.Scene, NewSceneReq, func(req kiwi.IRcvRequest) {
		core.SharePrcReq[*pb.NewSceneReq](req, common.SScene, _svc.OnNewScene)
	})
	kiwi.Router().BindReq(common.Scene, DisposeSceneReq, func(req kiwi.IRcvRequest) {
		core.SharePrcReq[*pb.DisposeSceneReq](req, common.SScene, _svc.OnDisposeScene)
	})
	kiwi.Router().BindReq(common.Scene, SceneGetReq, func(req kiwi.IRcvRequest) {
		core.SharePrcReq[*pb.SceneGetReq](req, common.SScene, _svc.OnSceneGet)
	})
	kiwi.Router().BindReq(common.Scene, SceneHasReq, func(req kiwi.IRcvRequest) {
		core.SharePrcReq[*pb.SceneHasReq](req, common.SScene, _svc.OnSceneHas)
	})
}
