// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package scene

import (
	"game/internal/common"

	"github.com/15mga/kiwi"
)

func (s *svc) bindReqToRes() {
	kiwi.Codec().BindReqToRes(common.Scene, SceneEntryReq, SceneEntryRes)
	kiwi.Codec().BindReqToRes(common.Scene, SceneMovementReq, SceneMovementRes)
	kiwi.Codec().BindReqToRes(common.Scene, SceneBehaviourReq, SceneBehaviourRes)
	kiwi.Codec().BindReqToRes(common.Scene, SceneRobotAddReq, SceneRobotAddRes)
	kiwi.Codec().BindReqToRes(common.Scene, SceneRobotClearReq, SceneRobotClearRes)
	kiwi.Codec().BindReqToRes(common.Scene, NewSceneReq, NewSceneRes)
	kiwi.Codec().BindReqToRes(common.Scene, DisposeSceneReq, DisposeSceneRes)
	kiwi.Codec().BindReqToRes(common.Scene, SceneGetReq, SceneGetRes)
	kiwi.Codec().BindReqToRes(common.Scene, SceneHasReq, SceneHasRes)
}
