// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package balancer

import (
	"game/internal/common"
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/core"
)

func (s *svc) registerPusAndReq() {
	kiwi.Router().BindReq(common.Balancer, BalanceRoomReq, func(req kiwi.IRcvRequest) {
		core.GoPrcReq[*pb.BalanceRoomReq](req, _svc.OnBalanceRoom)
	})
}
