// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package balancer

import (
	"game/internal/common"

	"github.com/15mga/kiwi"
)

func (s *svc) bindReqToRes() {
	kiwi.Codec().BindReqToRes(common.Balancer, BalanceRoomReq, BalanceRoomRes)
}
