// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package balancer

import (
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

func (s *svc) OnBalanceRoom(pkt kiwi.IRcvRequest, req *pb.BalanceRoomReq, res *pb.BalanceRoomRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}
