// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package player

const (
	//不存在的账号
	EcPlayer_NotExistId = 1
	//已存在的昵称
	EcPlayerNew_ExistNick = 1
	//不存在的账号
	EcPlayerId_NotExistId = 1
	//不存在token或玩家id
	EcPlayerReconnect_NotExist = 1
)
