// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package player

import (
	"github.com/15mga/kiwi/util/mgo"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

const (
	SchemaReconnect = "reconnect"
	SchemaPlayer    = "player"
)

const (
	Id           = "_id" //玩家id
	Avatar       = "avatar"
	Gender       = "gender"
	Hero         = "hero"           //玩家英雄角色
	LastAddr     = "last_addr"      //最后登录的地址，重复登录用
	LastGateNode = "last_gate_node" //最后连接的网关节点，重复登录用
	LastSignIn   = "last_sign_in"   //最后登录时间
	Nick         = "nick"           //昵称
	Status       = "status"         //玩家状态
	TeamId       = "team_id"
	UserId       = "user_id" //用户id

	ReconnectId        = "_id"       //player id
	ReconnectCache     = "cache"     //gate的Cache
	ReconnectHead      = "head"      //gate的Head
	ReconnectTimestamp = "timestamp" //断线的时间戳,必须使用MongoDB的格式
	ReconnectToken     = "token"     //账号服给的token
)

func (s *svc) initColl() {
	mgo.InitColl(SchemaReconnect, ReconnectIdx)
	mgo.InitColl(SchemaPlayer, PlayerIdx)
}

func ReconnectIdx() []mongo.IndexModel {
	return []mongo.IndexModel{
		{
			Keys: bson.D{
				{"token", 1},
			},
		},
		{
			Keys: bson.D{
				{"timestamp", 1},
			},
			Options: options.Index().
				SetExpireAfterSeconds(300),
		},
	}
}

func PlayerIdx() []mongo.IndexModel {
	return []mongo.IndexModel{
		{
			Keys: bson.D{
				{"nick", "text"},
			},
			Options: options.Index().
				SetUnique(true),
		},
		{
			Keys: bson.D{
				{"hero", 1},
			},
		},
		{
			Keys: bson.D{
				{"status", 1},
			},
		},
		{
			Keys: bson.D{
				{"last_sign_in", 1},
			},
		},
		{
			Keys: bson.D{
				{"last_addr", 1},
			},
		},
		{
			Keys: bson.D{
				{"team_id", 1},
			},
		},
		{
			Keys: bson.D{
				{"scene_id", 1},
			},
		},
	}
}
