// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package player

import (
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

func (s *svc) OnPlayer(pkt kiwi.IRcvRequest, req *pb.PlayerReq, res *pb.PlayerRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnPlayerMany(pkt kiwi.IRcvRequest, req *pb.PlayerManyReq, res *pb.PlayerManyRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnPlayerNew(pkt kiwi.IRcvRequest, req *pb.PlayerNewReq, res *pb.PlayerNewRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnPlayerChangeNick(pkt kiwi.IRcvRequest, req *pb.PlayerChangeNickReq, res *pb.PlayerChangeNickRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnPlayerId(pkt kiwi.IRcvRequest, req *pb.PlayerIdReq, res *pb.PlayerIdRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnPlayerReconnect(pkt kiwi.IRcvRequest, req *pb.PlayerReconnectReq, res *pb.PlayerReconnectRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnPlayerList(pkt kiwi.IRcvRequest, req *pb.PlayerListReq, res *pb.PlayerListRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnPlayerDisconnect(pkt kiwi.IRcvRequest, req *pb.PlayerDisconnectReq, res *pb.PlayerDisconnectRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}
