// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package player

import (
	"game/internal/common"

	"github.com/15mga/kiwi"
)

func (s *svc) bindReqToRes() {
	kiwi.Codec().BindReqToRes(common.Player, PlayerReq, PlayerRes)
	kiwi.Codec().BindReqToRes(common.Player, PlayerManyReq, PlayerManyRes)
	kiwi.Codec().BindReqToRes(common.Player, PlayerNewReq, PlayerNewRes)
	kiwi.Codec().BindReqToRes(common.Player, PlayerChangeNickReq, PlayerChangeNickRes)
	kiwi.Codec().BindReqToRes(common.Player, PlayerIdReq, PlayerIdRes)
	kiwi.Codec().BindReqToRes(common.Player, PlayerReconnectReq, PlayerReconnectRes)
	kiwi.Codec().BindReqToRes(common.Player, PlayerListReq, PlayerListRes)
	kiwi.Codec().BindReqToRes(common.Player, PlayerDisconnectReq, PlayerDisconnectRes)
}
