// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package gate

import (
	"game/internal/common"
	"game/proto/pb"

	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

const (
	HeartbeatReq           kiwi.TCode = 0
	HeartbeatRes           kiwi.TCode = 1
	GateBanAddrReq         kiwi.TCode = 100
	GateBanAddrRes         kiwi.TCode = 101
	GateSendToIdReq        kiwi.TCode = 102
	GateSendToIdRes        kiwi.TCode = 103
	GateSendToAddrReq      kiwi.TCode = 104
	GateSendToAddrRes      kiwi.TCode = 105
	GateSendToMultiIdReq   kiwi.TCode = 106
	GateSendToMultiIdRes   kiwi.TCode = 107
	GateSendToMultiAddrReq kiwi.TCode = 108
	GateSendToMultiAddrRes kiwi.TCode = 109
	GateSendToAllReq       kiwi.TCode = 110
	GateSendToAllRes       kiwi.TCode = 111
	GateCloseIdReq         kiwi.TCode = 112
	GateCloseIdRes         kiwi.TCode = 113
	GateCloseAddrReq       kiwi.TCode = 114
	GateCloseAddrRes       kiwi.TCode = 115
	GateUpdateReq          kiwi.TCode = 116
	GateUpdateRes          kiwi.TCode = 117
	GateAddrUpdateReq      kiwi.TCode = 118
	GateAddrUpdateRes      kiwi.TCode = 119
	GateRemoveReq          kiwi.TCode = 120
	GateRemoveRes          kiwi.TCode = 121
	GateAddrRemoveReq      kiwi.TCode = 122
	GateAddrRemoveRes      kiwi.TCode = 123
	GateGetReq             kiwi.TCode = 124
	GateGetRes             kiwi.TCode = 125
	GateAddrGetReq         kiwi.TCode = 126
	GateAddrGetRes         kiwi.TCode = 127
)

func (svc *svc) bindCodecFac() {
	kiwi.Codec().BindFac(common.Gate, HeartbeatReq, func() util.IMsg {
		return &pb.HeartbeatReq{}
	})
	kiwi.Codec().BindFac(common.Gate, HeartbeatRes, func() util.IMsg {
		return &pb.HeartbeatRes{}
	})
	kiwi.Codec().BindFac(common.Gate, GateBanAddrReq, func() util.IMsg {
		return &pb.GateBanAddrReq{}
	})
	kiwi.Codec().BindFac(common.Gate, GateBanAddrRes, func() util.IMsg {
		return &pb.GateBanAddrRes{}
	})
	kiwi.Codec().BindFac(common.Gate, GateSendToIdReq, func() util.IMsg {
		return &pb.GateSendToIdReq{}
	})
	kiwi.Codec().BindFac(common.Gate, GateSendToIdRes, func() util.IMsg {
		return &pb.GateSendToIdRes{}
	})
	kiwi.Codec().BindFac(common.Gate, GateSendToAddrReq, func() util.IMsg {
		return &pb.GateSendToAddrReq{}
	})
	kiwi.Codec().BindFac(common.Gate, GateSendToAddrRes, func() util.IMsg {
		return &pb.GateSendToAddrRes{}
	})
	kiwi.Codec().BindFac(common.Gate, GateSendToMultiIdReq, func() util.IMsg {
		return &pb.GateSendToMultiIdReq{}
	})
	kiwi.Codec().BindFac(common.Gate, GateSendToMultiIdRes, func() util.IMsg {
		return &pb.GateSendToMultiIdRes{}
	})
	kiwi.Codec().BindFac(common.Gate, GateSendToMultiAddrReq, func() util.IMsg {
		return &pb.GateSendToMultiAddrReq{}
	})
	kiwi.Codec().BindFac(common.Gate, GateSendToMultiAddrRes, func() util.IMsg {
		return &pb.GateSendToMultiAddrRes{}
	})
	kiwi.Codec().BindFac(common.Gate, GateSendToAllReq, func() util.IMsg {
		return &pb.GateSendToAllReq{}
	})
	kiwi.Codec().BindFac(common.Gate, GateSendToAllRes, func() util.IMsg {
		return &pb.GateSendToAllRes{}
	})
	kiwi.Codec().BindFac(common.Gate, GateCloseIdReq, func() util.IMsg {
		return &pb.GateCloseIdReq{}
	})
	kiwi.Codec().BindFac(common.Gate, GateCloseIdRes, func() util.IMsg {
		return &pb.GateCloseIdRes{}
	})
	kiwi.Codec().BindFac(common.Gate, GateCloseAddrReq, func() util.IMsg {
		return &pb.GateCloseAddrReq{}
	})
	kiwi.Codec().BindFac(common.Gate, GateCloseAddrRes, func() util.IMsg {
		return &pb.GateCloseAddrRes{}
	})
	kiwi.Codec().BindFac(common.Gate, GateUpdateReq, func() util.IMsg {
		return &pb.GateUpdateReq{}
	})
	kiwi.Codec().BindFac(common.Gate, GateUpdateRes, func() util.IMsg {
		return &pb.GateUpdateRes{}
	})
	kiwi.Codec().BindFac(common.Gate, GateAddrUpdateReq, func() util.IMsg {
		return &pb.GateAddrUpdateReq{}
	})
	kiwi.Codec().BindFac(common.Gate, GateAddrUpdateRes, func() util.IMsg {
		return &pb.GateAddrUpdateRes{}
	})
	kiwi.Codec().BindFac(common.Gate, GateRemoveReq, func() util.IMsg {
		return &pb.GateRemoveReq{}
	})
	kiwi.Codec().BindFac(common.Gate, GateRemoveRes, func() util.IMsg {
		return &pb.GateRemoveRes{}
	})
	kiwi.Codec().BindFac(common.Gate, GateAddrRemoveReq, func() util.IMsg {
		return &pb.GateAddrRemoveReq{}
	})
	kiwi.Codec().BindFac(common.Gate, GateAddrRemoveRes, func() util.IMsg {
		return &pb.GateAddrRemoveRes{}
	})
	kiwi.Codec().BindFac(common.Gate, GateGetReq, func() util.IMsg {
		return &pb.GateGetReq{}
	})
	kiwi.Codec().BindFac(common.Gate, GateGetRes, func() util.IMsg {
		return &pb.GateGetRes{}
	})
	kiwi.Codec().BindFac(common.Gate, GateAddrGetReq, func() util.IMsg {
		return &pb.GateAddrGetReq{}
	})
	kiwi.Codec().BindFac(common.Gate, GateAddrGetRes, func() util.IMsg {
		return &pb.GateAddrGetRes{}
	})
}
