// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package gate

const (
	//地址不存在
	EcGateBanAddr_NotExistAddr = 1
	//id不存在
	EcGateSendToId_NotExistId = 1
	//地址不存在
	EcGateSendToAddr_NotExistAddr = 1
	//id不存在
	EcGateUpdate_NotExistId = 1
	//地址不存在
	EcGateAddrUpdate_NotExistAddr = 1
	//id不存在
	EcGateRemove_NotExistId = 1
	//地址不存在
	EcGateAddrRemove_NotExistAddr = 1
	//id不存在
	EcGateGet_NotExistId = 1
	//地址不存在
	EcGateAddrGet_NotExistAddr = 1
)
