// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package gate

import (
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

func (s *svc) OnGateCloseId(pkt kiwi.IRcvPush, pus *pb.GateCloseIdPus) {
	pkt.Err2(util.EcNotImplement, util.M{"pus": pus})
}

func (s *svc) OnGateCloseAddr(pkt kiwi.IRcvPush, pus *pb.GateCloseAddrPus) {
	pkt.Err2(util.EcNotImplement, util.M{"pus": pus})
}
