// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package gate

import (
	"game/internal/common"
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/core"
)

func (s *svc) registerReq() {
	kiwi.Router().BindReq(common.Gate, HeartbeatReq, func(req kiwi.IRcvRequest) {
		core.SelfPrcReq[*pb.HeartbeatReq](req, _svc.OnHeartbeat)
	})
	kiwi.Router().BindReq(common.Gate, GateBanAddrReq, func(req kiwi.IRcvRequest) {
		core.SelfPrcReq[*pb.GateBanAddrReq](req, _svc.OnGateBanAddr)
	})
	kiwi.Router().BindReq(common.Gate, GateSendToIdReq, func(req kiwi.IRcvRequest) {
		core.SelfPrcReq[*pb.GateSendToIdReq](req, _svc.OnGateSendToId)
	})
	kiwi.Router().BindReq(common.Gate, GateSendToAddrReq, func(req kiwi.IRcvRequest) {
		core.SelfPrcReq[*pb.GateSendToAddrReq](req, _svc.OnGateSendToAddr)
	})
	kiwi.Router().BindReq(common.Gate, GateSendToMultiIdReq, func(req kiwi.IRcvRequest) {
		core.SelfPrcReq[*pb.GateSendToMultiIdReq](req, _svc.OnGateSendToMultiId)
	})
	kiwi.Router().BindReq(common.Gate, GateSendToMultiAddrReq, func(req kiwi.IRcvRequest) {
		core.SelfPrcReq[*pb.GateSendToMultiAddrReq](req, _svc.OnGateSendToMultiAddr)
	})
	kiwi.Router().BindReq(common.Gate, GateSendToAllReq, func(req kiwi.IRcvRequest) {
		core.SelfPrcReq[*pb.GateSendToAllReq](req, _svc.OnGateSendToAll)
	})
	kiwi.Router().BindReq(common.Gate, GateCloseIdReq, func(req kiwi.IRcvRequest) {
		core.SelfPrcReq[*pb.GateCloseIdReq](req, _svc.OnGateCloseId)
	})
	kiwi.Router().BindReq(common.Gate, GateCloseAddrReq, func(req kiwi.IRcvRequest) {
		core.SelfPrcReq[*pb.GateCloseAddrReq](req, _svc.OnGateCloseAddr)
	})
	kiwi.Router().BindReq(common.Gate, GateUpdateReq, func(req kiwi.IRcvRequest) {
		core.SelfPrcReq[*pb.GateUpdateReq](req, _svc.OnGateUpdate)
	})
	kiwi.Router().BindReq(common.Gate, GateAddrUpdateReq, func(req kiwi.IRcvRequest) {
		core.SelfPrcReq[*pb.GateAddrUpdateReq](req, _svc.OnGateAddrUpdate)
	})
	kiwi.Router().BindReq(common.Gate, GateRemoveReq, func(req kiwi.IRcvRequest) {
		core.SelfPrcReq[*pb.GateRemoveReq](req, _svc.OnGateRemove)
	})
	kiwi.Router().BindReq(common.Gate, GateAddrRemoveReq, func(req kiwi.IRcvRequest) {
		core.SelfPrcReq[*pb.GateAddrRemoveReq](req, _svc.OnGateAddrRemove)
	})
	kiwi.Router().BindReq(common.Gate, GateGetReq, func(req kiwi.IRcvRequest) {
		core.SelfPrcReq[*pb.GateGetReq](req, _svc.OnGateGet)
	})
	kiwi.Router().BindReq(common.Gate, GateAddrGetReq, func(req kiwi.IRcvRequest) {
		core.SelfPrcReq[*pb.GateAddrGetReq](req, _svc.OnGateAddrGet)
	})
}
