// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package user

import (
	"game/internal/common"
	"game/proto/pb"

	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

const (
	SignUpReq  kiwi.TCode = 0
	SignUpRes  kiwi.TCode = 1
	SignInReq  kiwi.TCode = 2
	SignInRes  kiwi.TCode = 3
	SignOutReq kiwi.TCode = 4
	SignOutRes kiwi.TCode = 5
	SignUpNtc  kiwi.TCode = 100
	SignInNtc  kiwi.TCode = 101
	SignOutNtc kiwi.TCode = 102
)

func (svc *svc) bindCodecFac() {
	kiwi.Codec().BindFac(common.User, SignUpReq, func() util.IMsg {
		return &pb.SignUpReq{}
	})
	kiwi.Codec().BindFac(common.User, SignUpRes, func() util.IMsg {
		return &pb.SignUpRes{}
	})
	kiwi.Codec().BindFac(common.User, SignInReq, func() util.IMsg {
		return &pb.SignInReq{}
	})
	kiwi.Codec().BindFac(common.User, SignInRes, func() util.IMsg {
		return &pb.SignInRes{}
	})
	kiwi.Codec().BindFac(common.User, SignOutReq, func() util.IMsg {
		return &pb.SignOutReq{}
	})
	kiwi.Codec().BindFac(common.User, SignOutRes, func() util.IMsg {
		return &pb.SignOutRes{}
	})
	kiwi.Codec().BindFac(common.User, SignUpNtc, func() util.IMsg {
		return &pb.SignUpNtc{}
	})
	kiwi.Codec().BindFac(common.User, SignInNtc, func() util.IMsg {
		return &pb.SignInNtc{}
	})
	kiwi.Codec().BindFac(common.User, SignOutNtc, func() util.IMsg {
		return &pb.SignOutNtc{}
	})
}
