// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package user

const (
	//账号错误
	EcSignUp_IdWrong = 1
	//密码错误
	EcSignUp_PwWrong = 2
	//账号已存在
	EcSignUp_IdExist = 3
	//账号或密码错误
	EcSignIn_WrongIdOrPassword = 1
)
