// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package user

import (
	"github.com/15mga/kiwi/util/mgo"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

const (
	SchemaUser = "user"
)

const (
	Id       = "_id"
	Ban      = "ban"
	Password = "password"
	RoleMask = "role_mask"
)

func (s *svc) initColl() {
	mgo.InitColl(SchemaUser, UserIdx)
}

func UserIdx() []mongo.IndexModel {
	return []mongo.IndexModel{
		{
			Keys: bson.D{
				{"ban", 1},
			},
			Options: options.Index().
				SetUnique(true),
		},
	}
}
