// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package user

import (
	"game/internal/common"
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/core"
)

func (s *svc) registerReq() {
	kiwi.Router().BindReq(common.User, SignUpReq, func(req kiwi.IRcvRequest) {
		core.GoPrcReq[*pb.SignUpReq](req, _svc.OnSignUp)
	})
	kiwi.Router().BindReq(common.User, SignInReq, func(req kiwi.IRcvRequest) {
		core.GoPrcReq[*pb.SignInReq](req, _svc.OnSignIn)
	})
	kiwi.Router().BindReq(common.User, SignOutReq, func(req kiwi.IRcvRequest) {
		core.GoPrcReq[*pb.SignOutReq](req, _svc.OnSignOut)
	})
}
