// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package user

import (
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

func (s *svc) OnSignUp(pkt kiwi.IRcvRequest, req *pb.SignUpReq, res *pb.SignUpRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnSignIn(pkt kiwi.IRcvRequest, req *pb.SignInReq, res *pb.SignInRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnSignOut(pkt kiwi.IRcvRequest, req *pb.SignOutReq, res *pb.SignOutRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}
