// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package common

import (
	"github.com/15mga/kiwi"
)

func RoleToStr(role int64) string {
	switch role {
	case RPlayer:
		return "player"
	case RAdmin:
		return "admin"
	case RGuest:
		return "guest"
	default:
		return ""
	}
}

func StrToRole(role string) int64 {
	switch role {
	case "player":
		return RPlayer
	case "admin":
		return RAdmin
	case "guest":
		return RGuest
	default:
		return 0
	}
}

var MsgRole = map[kiwi.TSvcCode][]int64{
	2000: {RPlayer, RAdmin},
	3000: {RGuest},
	3002: {RGuest},
	3004: {RPlayer},
	4000: {RPlayer, RAdmin},
	4002: {RPlayer, RAdmin},
	4004: {RPlayer},
	4006: {RPlayer, RAdmin},
	4008: {RPlayer, RAdmin},
	4010: {RPlayer},
	4100: {RAdmin},
	5000: {RPlayer, RAdmin},
	5002: {RPlayer, RAdmin},
	5004: {RPlayer},
	5007: {RPlayer},
	5010: {RPlayer},
	5013: {RPlayer},
	5016: {RPlayer},
	5018: {RPlayer},
	5021: {RPlayer},
	7000: {RPlayer},
	7003: {RPlayer},
	7005: {RPlayer},
	7007: {RPlayer},
	8000: {RPlayer},
	9000: {RPlayer, RAdmin},
}
