// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package chat

import (
	"github.com/15mga/kiwi/util/mgo"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
)

const (
	SchemaChan = "chan"
	SchemaMsg  = "msg"
)

const (
	ChanId       = "_id"
	ChanChanType = "chan_type"
	ChanMembers  = "members"

	MsgId              = "_id"
	MsgChId            = "ch_id"     //chan id
	MsgChanType        = "chan_type" //消息类型 1:文本 2:语音
	MsgMsg             = "msg"
	MsgPublisher       = "publisher"        //消息发送者
	MsgPublisherAvatar = "publisher_avatar" //消息发送者图标
	MsgPublisherId     = "publisher_id"     //消息发送者id
)

func (s *svc) initColl() {
	mgo.InitColl(SchemaChan, ChanIdx)
	mgo.InitColl(SchemaMsg, MsgIdx)
}

func ChanIdx() []mongo.IndexModel {
	return []mongo.IndexModel{
		{
			Keys: bson.D{
				{"type", 1},
			},
		},
	}
}

func MsgIdx() []mongo.IndexModel {
	return []mongo.IndexModel{
		{
			Keys: bson.D{
				{"chan_id", 1},
			},
		},
		{
			Keys: bson.D{
				{"player_id", 1},
			},
		},
		{
			Keys: bson.D{
				{"chan_id", 1},
				{"player_id", 1},
			},
		},
	}
}
