// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package chat

import (
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

func (s *svc) OnMsg(pkt kiwi.IRcvPush, pus *pb.MsgPus) {
	pkt.Err2(util.EcNotImplement, util.M{"pus": pus})
}
