// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package chat

import (
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

func (s *svc) OnNewMsg(pkt kiwi.IRcvRequest, req *pb.NewMsgReq, res *pb.NewMsgRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}

func (s *svc) OnNewChan(pkt kiwi.IRcvRequest, req *pb.NewChanReq, res *pb.NewChanRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}
