// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package chat

import (
	"game/internal/common"
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/core"
	"github.com/15mga/kiwi/util"
)

func (s *svc) registerReq() {
	kiwi.Router().BindReq(common.Chat, NewMsgReq, func(req kiwi.IRcvRequest) {
		key, _ := util.MGet[string](req.Head(), "cid")
		core.SharePrcReq[*pb.NewMsgReq](req, key, _svc.OnNewMsg)
	})
	kiwi.Router().BindReq(common.Chat, NewChanReq, func(req kiwi.IRcvRequest) {
		key, _ := util.MGet[string](req.Head(), "cid")
		core.SharePrcReq[*pb.NewChanReq](req, key, _svc.OnNewChan)
	})
}
