// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package team

import (
	"game/internal/common"
	"game/proto/pb"

	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

const (
	NewTeamReq kiwi.TCode = 0
	NewTeamRes kiwi.TCode = 1
)

func (svc *svc) bindCodecFac() {
	kiwi.Codec().BindFac(common.Team, NewTeamReq, func() util.IMsg {
		return &pb.NewTeamReq{}
	})
	kiwi.Codec().BindFac(common.Team, NewTeamRes, func() util.IMsg {
		return &pb.NewTeamRes{}
	})
}
