// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package team

import (
	"github.com/15mga/kiwi/util/mgo"
	"go.mongodb.org/mongo-driver/mongo"
)

const (
	SchemaTeam = "team"
)

const (
	Id      = "_id"
	Mode    = "mode"
	Players = "players"

	TeamPlayerOnline   = "online"
	TeamPlayerPlayerId = "player_id"
)

func (s *svc) initColl() {
	mgo.InitColl(SchemaTeam, TeamIdx)
}

func TeamIdx() []mongo.IndexModel {
	return []mongo.IndexModel{}
}
