// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package team

import (
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/core"
	"github.com/15mga/kiwi/util"
)

func (svc *svc) watchNtc() {
	kiwi.Router().WatchNotice(&pb.PlayerDisconnectNtc{}, func(ntc kiwi.IRcvNotice) {
		key, ok := util.MGet[string](ntc.Head(), "sid")
		if ok {
			core.ActivePrcNtc[*pb.PlayerDisconnectNtc](ntc, key, _svc.OnPlayerDisconnectNtc)
		}
	})
	kiwi.Router().WatchNotice(&pb.PlayerOfflineNtc{}, func(ntc kiwi.IRcvNotice) {
		key, ok := util.MGet[string](ntc.Head(), "tid")
		if ok {
			core.ActivePrcNtc[*pb.PlayerOfflineNtc](ntc, key, _svc.OnPlayerOfflineNtc)
		}
	})
}
