// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package team

import (
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/util"
)

func (s *svc) OnNewTeam(pkt kiwi.IRcvRequest, req *pb.NewTeamReq, res *pb.NewTeamRes) {
	pkt.Err2(util.EcNotImplement, util.M{"req": req})
}
