// Code generated by protoc-gen-go-kiwi. DO NOT EDIT.

package team

import (
	"game/internal/common"
	"game/proto/pb"
	"github.com/15mga/kiwi"
	"github.com/15mga/kiwi/core"
	"github.com/15mga/kiwi/util"
)

func (s *svc) registerReq() {
	kiwi.Router().BindReq(common.Team, NewTeamReq, func(req kiwi.IRcvRequest) {
		key, _ := util.MGet[string](req.Head(), "rid")
		core.ActivePrcReq[*pb.NewTeamReq](req, key, _svc.OnNewTeam)
	})
}
